### Create File(media....)
POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testvideo.mp4"

< C:\Users\Rajabbek\Desktop\img\testvideo.mp4

### Create File(photo....)
POST http://localhost:8080/attach/any/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.png"

< C:\Users\Rajabbek\Desktop\img\1.png

### Get By Id(Open)
GET http://localhost:8080/attach/any/5112368f-a066-4c26-b239-5246fd093cdd.jpg

### Get All file (Open)
GET http://localhost:8080/attach/any/general/314d33d2-7a93-4754-8317-60d08f6500ef.jpg

### Download
GET http://localhost:8080/attach/any/download/314d33d2-7a93-4754-8317-60d08f6500ef.jpg
Accept-Language: UZ

### Get All Pagination(Admin)
GET http://localhost:8080/attach/adm
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MDQ5NzMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2OTEzNzMsImlzcyI6IllvdXR1YmUifQ.beLofz__ok54_FERCOFt_jnDMdLlPZro1i15tYvqc2_0-vX7H67SxN21Ow8y5LGb-sZOtjSKyoxlp57raVRXNA

### Delete By Id (Admin)
DELETE http://localhost:8080/attach/adm/314d33d2-7a93-4754-8317-60d08f6500ef
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1MDM3OTMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg1OTAxOTMsImlzcyI6IllvdXR1YmUifQ.sPu5hJnyzhY8-d1MYBm18ciuiPjZxeqy15Cp9GMkruqASNhOrpair3Y-RYPuEkDzy7wzzHlNpRAKklTV3mPylg

### getUrl
GET http://localhost:8080/attach/getUrl/2f7fe3f8-1f3d-4a54-b4bd-5a083aa143c2








