### Create File(photo,media....)
POST http://localhost:8080/attach/any/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="rasm2.jpg"

< C:\Users\Aslbek\Desktop\Teskshirish\rasm2.jpg

### Get By Id(Open)
GET http://localhost:8080/attach/any/5112368f-a066-4c26-b239-5246fd093cdd.jpg

### Get All file (Open)
GET http://localhost:8080/attach/any/general/314d33d2-7a93-4754-8317-60d08f6500ef.jpg









