### registration profile
POST localhost:8080/auth/registration
Content-Type: application/json
Accept-Language: UZ

{
  "name": "Shamshod",
  "surname": "Shamshod",
  "email": "shamshod6696odinayev@gmail.com",
  "password": "123456"
}

### verification profile
GET localhost:8080/auth/verification/email/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0MzIwNTgsImlkIjozMSwiZXhwIjoxNzA4NDM1NjU4LCJpc3MiOiJZb3V0dWJlIn0.ntO0gT0GsoVYOC_Yu5E3-R-v8mBcRIfHAXUusDu9onyP1UM4FMRr2MulNbd6MozyyRZhqEe59mBi3mn2PAfSIQ
Accept-Language: UZ

### login profile
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "email": "adminjon@gmail.com",
  "password": "@Root123"
}
