### registration profile
POST localhost:8080/auth/registration
Content-Type: application/json
Accept-Language: UZ

{
  "name": "Aslbek",
  "surname": "Norqulov",
  "email": "ahrororzimurodov@icloud.com",
  "password": "Asl123"
}

### verification profile
GET localhost:8080/auth/verification/email/UZ/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0MzM0MDgsImlkIjozLCJleHAiOjE3MDg0MzcwMDgsImlzcyI6IllvdXR1YmUifQ.IEQ8Dw_j9o-6hS-pe-hEnljY8soBe77FIwlTPsz-jvkjNLtnTBTrLaS3JtBr85b022A0JYjtM2nc3lnWcpguEQ
Accept-Language: UZ