### registration profile
POST localhost:8080/auth/registration
Content-Type: application/json
Accept-Language: UZ

{
  "name": "rajab",
  "surname": "ollanzarov",
  "email": "rajabbekollanazarov12@gmail.com",
  "password": "123456",
  "mainPhoto": "uploads/2024/2/23/2f7fe3f8-1f3d-4a54-b4bd-5a083aa143c2.png"
}

### verification profile
GET localhost:8080/auth/verification/email/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0MzIwNTgsImlkIjozMSwiZXhwIjoxNzA4NDM1NjU4LCJpc3MiOiJZb3V0dWJlIn0.ntO0gT0GsoVYOC_Yu5E3-R-v8mBcRIfHAXUusDu9onyP1UM4FMRr2MulNbd6MozyyRZhqEe59mBi3mn2PAfSIQ


### login profile
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "email": "aslbeknorqulov246@gmail.com",
  "password": "123456"
}

### login profile
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "email": "rajabbekollanazarov12@gmail.com",
  "password": "123456"
}

#### Admin login
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "email": "adminjon@gmail.com",
  "password": "admin123"
}

#### Moderator login
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "email": "moderatorjon@gmail.com",
  "password": "moderator123"
}

