### Create
POST localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3Njg1NTMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg4NTQ5NTMsImlzcyI6IllvdXR1YmUifQ.bLhau3IdNbokj20ycBmU24SgZ4t9JTVt4dumOTSRQPlyZdJzv-9Vm3W_VipeFIQVOHA_wTevVLotAJPyJfqAEg

{
  "nameUz": "Sport",
  "nameRu": "Cпорт",
  "nameEn": "Sport"
}

### Update
PUT localhost:8080/category/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0NDA2NjcsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg1MjcwNjcsImlzcyI6IllvdXR1YmUifQ.W6hXPYuOsmxvkMfw1HYEQo5ISAwTmjyVKn3ugm4HXydNKfOKfyGmqU-f3Q1EjAReloFIUX5yMrnuR_v8dcuqcA

{
  "nameEn": "Musiqa",
  "nameRu": "Музыка",
  "nameUz": "Music"
}


### Delete category
DELETE localhost:8080/category/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg0NDA2NjcsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg1MjcwNjcsImlzcyI6IllvdXR1YmUifQ.W6hXPYuOsmxvkMfw1HYEQo5ISAwTmjyVKn3ugm4HXydNKfOKfyGmqU-f3Q1EjAReloFIUX5yMrnuR_v8dcuqcA

### Get list
GET localhost:8080/category/any?lan=UZ
