### crate comment
POST localhost:8080/comment
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDk0NjczMjIsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDk1NTM3MjIsImlzcyI6IllvdXR1YmUifQ.TfEy5RiJ29ZIvBL85t4WbeiJzWYe9tjU5flVv5v60tlaXWcJAKDTdlZ4mcKH1TU9vVED6JPsGog_gqUrQrgQXg

{
  "videoId": "51208383-f4e7-4e2e-b1a5-6e8bdb09155b",
  "content": "Tureeeeee"
}

### update Comment
PUT localhost:8080/comment/1
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4OTM1MjgsImVtYWlsIjoiYXNsYmVrbm9ycXVsb3YyNDZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODk3OTkyOCwiaXNzIjoiWW91dHViZSJ9.1VYkemMQSsigKCpHf6MifAAy7-7WpFOT8mIfP2FRIcnlGcpnT7I3wqFg75lnG4vkspvmHKewds4eja-zNCHnyA

{
  "content": "Tre"
}

### Delete Comment (USER AND OWNER, ADMIN)
DELETE localhost:8080/comment/2
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4OTkzNTMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg5ODU3NTMsImlzcyI6IllvdXR1YmUifQ.asLyzd2FeE4by9oirCO4B8S-Jw13xo8xG_udoueTiVjVReeMERvT-mCyo9SwGZ0lRf5Xv5BBmCxEEVwiPzTl6A

### Comment List Pagination (ADMIN)
GET localhost:8080/comment?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4OTkzNTMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg5ODU3NTMsImlzcyI6IllvdXR1YmUifQ.asLyzd2FeE4by9oirCO4B8S-Jw13xo8xG_udoueTiVjVReeMERvT-mCyo9SwGZ0lRf5Xv5BBmCxEEVwiPzTl6A

### Comment List By profileId(ADMIN)
GET localhost:8080/comment/4
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5NDY3MzIsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkwMzMxMzIsImlzcyI6IllvdXR1YmUifQ.Saz0MharWQTx34TIz7fVRrP12P9f_rFAgefhNUgYm-CLuvLWVOmlSQNo6ppV6Suw_eNz9DSQRnGz1OeniG2sOg

### Comment List By Profile (murojat qilgan odamning comment lari)
GET localhost:8080/comment/byProfile
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5NDY3MzIsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkwMzMxMzIsImlzcyI6IllvdXR1YmUifQ.Saz0MharWQTx34TIz7fVRrP12P9f_rFAgefhNUgYm-CLuvLWVOmlSQNo6ppV6Suw_eNz9DSQRnGz1OeniG2sOg

### Comment List by videoId
GET localhost:8080/comment/byVideoId/f1dccd77-f828-4a31-92ea-6b2ce819ed05
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5NDY3MzIsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkwMzMxMzIsImlzcyI6IllvdXR1YmUifQ.Saz0MharWQTx34TIz7fVRrP12P9f_rFAgefhNUgYm-CLuvLWVOmlSQNo6ppV6Suw_eNz9DSQRnGz1OeniG2sOg

###  Get Comment Replied Comment by comment Id
GET localhost:8080/comment/commentId?commentId=1
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5NDY3MzIsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkwMzMxMzIsImlzcyI6IllvdXR1YmUifQ.Saz0MharWQTx34TIz7fVRrP12P9f_rFAgefhNUgYm-CLuvLWVOmlSQNo6ppV6Suw_eNz9DSQRnGz1OeniG2sOg
