### get email history pagination (ADMIN)
GET localhost:8080/emailHistory/adm/pagination?page=2&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTc2NzksImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2ODQwNzksImlzcyI6IllvdXR1YmUifQ.-Dcxd1jKymqY-_cx7lezXCwGIYjzTDgRqLzLkiS70pGneuVfiPsns6DYqW6hPBJN6n7HYcjI4jBBDGI97ILYYQ