### get email history pagination (ADMIN)
GET localhost:8080/emailHistory/adm/pagination?page=2&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTc2NzksImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2ODQwNzksImlzcyI6IllvdXR1YmUifQ.-Dcxd1jKymqY-_cx7lezXCwGIYjzTDgRqLzLkiS70pGneuVfiPsns6DYqW6hPBJN6n7HYcjI4jBBDGI97ILYYQ

### get by email pagination
POST localhost:8080/emailHistory/paginationByEmail?page=1&size=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MDQ3NzEsImVtYWlsIjoiYXNsYmVrbm9ycXVsb3YyNDZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODY5MTE3MSwiaXNzIjoiWW91dHViZSJ9.WFPFcv5anUO8idOfz6kT6qfeHQbBORzMnGZGSlef84SKltrrUsQfP7358yYCQjQb0tlztCC-LEn8lHsmu3GcwQ

{
  "email": "aslbeknorqulov24@gmail.com"
}