### Create Playlist
POST localhost:8080/playlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkwNDMzODMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkxMjk3ODMsImlzcyI6IllvdXR1YmUifQ.gr9h9XWwIQ1rEzHhNLQtQPPpTQEMFX7b5OBk6T5kW4RS_HvyK4__GecsnA-yXK3n7qtvmO6vQawCh7caPs3spA
Accept-Language: UZ

{
  "channelId": 1,
  "description": "aaaa",
  "name": "aaaaa",
  "status": "PUBLIC",
  "orderNum": 1
}

### Change Playlist Status
PUT localhost:8080/playlist/changeStatus/1?status=PRIVATE
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4NjI4NDEsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg5NDkyNDEsImlzcyI6IllvdXR1YmUifQ.i70F4nRdXZ71-6M4SKolSWu73P09cRuwb4e-pTYV29OVB0BlBP7Sr3tmTrc_8Ne1Dx_cFJUsrRi2A6D3lWWVEQ

### Delete Playlist
DELETE localhost:8080/playlist/1
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4NjQ5NTgsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg5NTEzNTgsImlzcyI6IllvdXR1YmUifQ.ljwomDxnDMwUaptmlhvUbOZYSel_8JCCePU69BFc95Wd8XakJIynzTj4X3-bpWabmjU4LjNC1o8ERHyYBo_6ig

### Playlist pagination
GET localhost:8080/playlist/playlistPagination?page=2&size=3
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkyODgyMDEsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkzNzQ2MDEsImlzcyI6IllvdXR1YmUifQ.0FzlrvSWecx66g3Y5KAhZuMLnc4EBk2yXrew4wtEnQrbio_6WythGVTAreIdEkZq6i9GvwaZF-Idi806QOABuA

### Playlist List By UserId
GET localhost:8080/playlist/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkyODgyMDEsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkzNzQ2MDEsImlzcyI6IllvdXR1YmUifQ.0FzlrvSWecx66g3Y5KAhZuMLnc4EBk2yXrew4wtEnQrbio_6WythGVTAreIdEkZq6i9GvwaZF-Idi806QOABuA

### Get User Playlist
GET localhost:8080/playlist/getAll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkyODgyMDEsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkzNzQ2MDEsImlzcyI6IllvdXR1YmUifQ.0FzlrvSWecx66g3Y5KAhZuMLnc4EBk2yXrew4wtEnQrbio_6WythGVTAreIdEkZq6i9GvwaZF-Idi806QOABuA

### get by id
GET localhost:8080/playlist/get/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDk0NTkzOTAsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDk1NDU3OTAsImlzcyI6IllvdXR1YmUifQ.7qxbWCyDM8RklJLhQNRw_mZ4uh0G6HjJ4G1_2UyzpC8cSBi_c1BteuAlMuqaNhMBDHZGIfJCfV-Pdp9uXV6tow
