### Change password
PUT localhost:8080/profile/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1MDI1MjQsImVtYWlsIjoic2hhbXNob2Q2Njk2b2RpbmF5ZXZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODU4ODkyNCwiaXNzIjoiWW91dHViZSJ9.kVF0Ydtlw6YMJKiV8xdgJxs_V7GKvUoT9GesUEVnTsdT9juJmLQqwdQGMm-Pwxmwt12Lh-Ouk7XFfahxx5SqsA
Accept-Language: UZ

{
  "oldPassword": "123456",
  "newPassword": "1111",
  "newPasswordConfirm": "1111"
}

### Update email
PUT localhost:8080/profile/updateEmail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MDAxMTMsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODY4NjUxMywiaXNzIjoiWW91dHViZSJ9.6U9GLhKUmVnCqB03j2hFZxyhsilPvlQ9sahxrjNYGdvebnjwWfFAP1IVXD4dmzIxDWK_5jmEt7FmGy6Xa9QOsQ
Accept-Language: UZ

{
  "email": "shamshod6696odinayev@gmail.com"
}

### Verification
GET localhost:8080/profile/verification/email/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTc4NDQsImlkIjoxMCwiZXhwIjoxNzA4NjAxNDQ0LCJpc3MiOiJZb3V0dWJlIn0.pkf8v_pRp-PkWJGa8Sc3b7xoC59rqMQoMT-dQOqteiG3liFYDR6q_IJQxdLpUrlDi6xPvMakjUtYc532sX5Idw

### Update name and surname
PUT localhost:8080/profile/changeNameAndSurname
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1MTA2NjcsImVtYWlsIjoiYXNsYmVrbm9ycXVsb3YyNDZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODU5NzA2NywiaXNzIjoiWW91dHViZSJ9.vhWxXfxfCmxH4G-c9lfMskKVbLeuj08a3j7jwJirFvKmUo9kaKQNCXxiIUv1kuvRk-J4FDhF7Yrw4pWgJPFtOw
Accept-Language: UZ

{
  "name": "Aslbek",
  "surname": "Norqulov"
}

### create profile admin
POST localhost:8080/profile/adm/createProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1MjE5MjUsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2MDgzMjUsImlzcyI6IllvdXR1YmUifQ.iQZu-I5jHNdg4UyMbaaahqLcymQuzhGb7EuWrl-tipLn3k6xFWhHaRk8Zhpz_BEKVMojHJZ3l8ocECN15fbK2w

{
  "name": "Aslbek",
  "surname": "Norqulov",
  "email": "norqulovaslbek920@gmail.com",
  "password": "123456",
  "profileRole": "ROLE_MODERATOR"
}
