###Create
POST http://localhost:8080/tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2MDQ3NjksImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2OTExNjksImlzcyI6IllvdXR1YmUifQ.7tqWpVnTv5zIakpdMwYPjysLOted1xNyWoWH-cgZ4e5CRGZ4JlNy6U7E5Kq4_pUHnjmFV1L6hQLK_q_XuMvieA

{
  "name": "detrf"
}


###Update
POST http://localhost:8080/tag/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTg2MjMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2ODUwMjMsImlzcyI6IllvdXR1YmUifQ.5e5VoYsCb06x7aybandreH_eczVqYTBHsQ-TVQ7qnR2YqJ7V-vrmBtSZEMlVLcB5gEllOayKFjcA0kJj3pWuVg

{
  "name": "tag yaratish"

}

###Delete
DELETE http://localhost:8080/tag/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTg2MjMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2ODUwMjMsImlzcyI6IllvdXR1YmUifQ.5e5VoYsCb06x7aybandreH_eczVqYTBHsQ-TVQ7qnR2YqJ7V-vrmBtSZEMlVLcB5gEllOayKFjcA0kJj3pWuVg

###Get List
GET http://localhost:8080/tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTg2MjMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2ODUwMjMsImlzcyI6IllvdXR1YmUifQ.5e5VoYsCb06x7aybandreH_eczVqYTBHsQ-TVQ7qnR2YqJ7V-vrmBtSZEMlVLcB5gEllOayKFjcA0kJj3pWuVg
