###Create
POST http://localhost:8080/tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3Nzc4OTcsImVtYWlsIjoicmFqYWJiZWtvbGxhbmF6YXJvdjEyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDg4NjQyOTcsImlzcyI6IllvdXR1YmUifQ.wd6-oFxZE9xTTZvy_fV5HrVmnGaL_Kgb8ROHMwLBSy9wYRbb6jzhuDvjJzgOf5Pvtw3wzATrroxf3kChQAl2ug

{
  "name": ["#java","#python"]
}


###Update
POST http://localhost:8080/tag/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTg2MjMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2ODUwMjMsImlzcyI6IllvdXR1YmUifQ.5e5VoYsCb06x7aybandreH_eczVqYTBHsQ-TVQ7qnR2YqJ7V-vrmBtSZEMlVLcB5gEllOayKFjcA0kJj3pWuVg

{
  "name": "tag yaratish"

}

###Delete
DELETE http://localhost:8080/tag/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg1OTg2MjMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg2ODUwMjMsImlzcyI6IllvdXR1YmUifQ.5e5VoYsCb06x7aybandreH_eczVqYTBHsQ-TVQ7qnR2YqJ7V-vrmBtSZEMlVLcB5gEllOayKFjcA0kJj3pWuVg

###Get List
GET http://localhost:8080/tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkxNzc2MzksImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkyNjQwMzksImlzcyI6IllvdXR1YmUifQ.eJkFuIS-mTPpJQZbngdIYQr6ZxigzaglaAfZ6YqJewdcSqZlI_ED-6HmWD5rEp5PAMjJ74ntAZfR3p-N986BHg
