### Create video (User)
POST http://localhost:8080/video
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDk0NjczMjIsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDk1NTM3MjIsImlzcyI6IllvdXR1YmUifQ.TfEy5RiJ29ZIvBL85t4WbeiJzWYe9tjU5flVv5v60tlaXWcJAKDTdlZ4mcKH1TU9vVED6JPsGog_gqUrQrgQXg

{
  "title": "cccc",
  "description": "ccccc",
  "attachId": "b9f7d8e8-ef35-4586-917a-bf1e8174965f",
  "categoryId": 4,
  "previewAttachId": "e62d6132-61c8-47ef-88c3-b2ce3fb94bca",
  "channelId": 2,
  "status": "PRIVATE",
  "type": "VIDEO"
}

### Update Status Video
PUT http://localhost:8080/video/updateStatus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3Nzc4OTcsImVtYWlsIjoicmFqYWJiZWtvbGxhbmF6YXJvdjEyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDg4NjQyOTcsImlzcyI6IllvdXR1YmUifQ.wd6-oFxZE9xTTZvy_fV5HrVmnGaL_Kgb8ROHMwLBSy9wYRbb6jzhuDvjJzgOf5Pvtw3wzATrroxf3kChQAl2ug

{
  "id": "74782efe-13a3-452c-9bc2-b086808d1a2a",
  "status": "PUBLIC"
}

### Get Video Pagination by CategoryId  VideShortInfo
GET localhost:8080/video/getCategoryId?page=1&size=3&id=6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3ODY2MTQsImVtYWlsIjoibW9kZXJhdG9yam9uQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODg3MzAxNCwiaXNzIjoiWW91dHViZSJ9.eGtc_WBxbHDL28ciRG7O0uMvYBlGJrx3YChzLdo3duWzzQ-TzYtIa5N7NCYNXc1CqEgK6jGDthYYBRfdVXQNBg
Accept-Language: UZ

### Search video by title
POST http://localhost:8080/video/searchByTitle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg3Nzc4OTcsImVtYWlsIjoicmFqYWJiZWtvbGxhbmF6YXJvdjEyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDg4NjQyOTcsImlzcyI6IllvdXR1YmUifQ.wd6-oFxZE9xTTZvy_fV5HrVmnGaL_Kgb8ROHMwLBSy9wYRbb6jzhuDvjJzgOf5Pvtw3wzATrroxf3kChQAl2ug

{
  "title": "bbc"
}

### Get video by tag_id with pagination
GET http://localhost:8080/video/462c6a3e-6702-43e8-b1e6-07f185d2a675
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4NjU5NTAsImVtYWlsIjoicmFqYWJiZWtvbGxhbmF6YXJvdjEyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDg5NTIzNTAsImlzcyI6IllvdXR1YmUifQ.cNwWTVzCrlJHy-TiIA4KA0-KhEMph8oTPtp1i4t4RgRtPcXAf7k-aWqm_cZMqxgvGA9QhsXyxcg8w4OAMBNuuw
Accept-Language: EN

###  Get Video List Pagination (ADMIN)
GET http://localhost:8080/video?page=1&size=6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4NjkyNDMsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg5NTU2NDMsImlzcyI6IllvdXR1YmUifQ.cChCaGIi0omytS6ldHPrbpZpnlP0DJ6_d1u0B-pecKHbbdCuJeuWeT5NQEG25_NF9INXEFY8hEV9u5717TcDOQ
Accept-Language: UZ

### Get vido play list Pagination
GET localhost:8080/video/getChannelVideoListPagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg4ODc3NzQsImVtYWlsIjoiYXNsYmVrbm9ycXVsb3YyNDZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODk3NDE3NCwiaXNzIjoiWW91dHViZSJ9.IDVpW7DLbr1BWu7Xs4kMr6-QKcnbSqm-1Rdglzh7WIZQo-ajiOzWi21mHECfSv8SCTdVcng4fCxSxgkd2VwpYg
Accept-Language: EN

###  Get Video By id (If Status PRIVATE allow only for OWNER or ADMIN)
GET localhost:8080/video/getVideoById/fb65c69e-9881-4814-a348-95036da86277
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkwNDc3MjgsImVtYWlsIjoiYWRtaW5qb25AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkxMzQxMjgsImlzcyI6IllvdXR1YmUifQ.lZShyBmAtL_RzrUgXWSsABs11DKhin0FOFKw0WedHAv36_K7sv1mTKxmPOiB_tGBu20RWEhecwJoWb9BOCRueg
Accept-Language: UZ